blueprint:
  name: Philips Hue v2 Smart Dimmer Switch and Remote (RWL022)
  description: Philips Hue v2 Smart Dimmer Switch and Remote (RWL022)
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch v2
      description: Pick the Hue Dimmer Switch v2 (RWL022)
      selector:
        device:
          integration: hue
    button_1_initial_press:
      name: Power initial press
      description: Action to run on initial press (occurs also before long press)
      default: []
      selector:
        action: {}
    button_1_long_press:
      name: Power long press
      description: Action to run on long press
      default: []
      selector:
        action: {}
    button_1_repeat:
      name: Power repeat (occurs on long press)
      description: Action to run on repeat
      default: []
      selector:
        action: {}
    button_1_short_release:
      name: Power short release
      description: Action to run on short release
      default: []
      selector:
        action: {}
    button_1_long_release:
      name: Power long release
      description: Action to run on long release
      default: []
      selector:
        action: {}
    button_2_initial_press:
      name: Brightness up initial press
      description: Action to run on initial press (occurs also before long press)
      default: []
      selector:
        action: {}
    button_2_long_press:
      name: Brightness up long press
      description: Action to run on long press
      default: []
      selector:
        action: {}
    button_2_repeat:
      name: Brightness up repeat (occurs on long press)
      description: Action to run on repeat
      default: []
      selector:
        action: {}
    button_2_short_release:
      name: Brightness up short release
      description: Action to run on short release
      default: []
      selector:
        action: {}
    button_2_long_release:
      name: Brightness up long release
      description: Action to run on long release
      default: []
      selector:
        action: {}
    button_3_initial_press:
      name: Brightness down initial press
      description: Action to run on initial press (occurs also before long press)
      default: []
      selector:
        action: {}
    button_3_long_press:
      name: Brightness down long press
      description: Action to run on long press
      default: []
      selector:
        action: {}
    button_3_repeat:
      name: Brightness down repeat (occurs on long press)
      description: Action to run on repeat
      default: []
      selector:
        action: {}
    button_3_short_release:
      name: Brightness down short release
      description: Action to run on short release
      default: []
      selector:
        action: {}
    button_3_long_release:
      name: Brightness down long release
      description: Action to run on long release
      default: []
      selector:
        action: {}
    button_4_initial_press:
      name: Hue initial press
      description: Action to run on initial press (occurs also before long press)
      default: []
      selector:
        action: {}
    button_4_long_press:
      name: Hue long press
      description: Action to run on long press
      default: []
      selector:
        action: {}
    button_4_repeat:
      name: Hue repeat (occurs on long press)
      description: Action to run on repeat
      default: []
      selector:
        action: {}
    button_4_short_release:
      name: Hue short release
      description: Action to run on short release
      default: []
      selector:
        action: {}
    button_4_long_release:
      name: Hue long release
      description: Action to run on long release
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: hue_event
    event_data:
      device_id: !input "remote"
action:
  - variables:
      type: "{{ trigger.event.data.type }}"
      subtype: "{{ trigger.event.data.subtype }}"
  - choose:
      - conditions: "{{ subtype == 1 }}"
        sequence:
          - chosse:
              - conditions: "{{ type == 'initial_press' }}"
                sequence: !input "button_1_initial_press"
              - conditions: "{{ type == 'long_press' }}"
                sequence: !input "button_1_long_press"
              - conditions: "{{ type == 'repeat' }}"
                sequence: !input "button_1_repeat"
              - conditions: "{{ type == 'short_release' }}"
                sequence: !input "button_1_short_release"
              - conditions: "{{ type == 'long_release' }}"
                sequence: !input "button_1_long_release"
      - conditions: "{{ subtype == 2 }}"
        sequence:
          - chosse:
              - conditions: "{{ type == 'initial_press' }}"
                sequence: !input "button_2_initial_press"
              - conditions: "{{ type == 'long_press' }}"
                sequence: !input "button_2_long_press"
              - conditions: "{{ type == 'repeat' }}"
                sequence: !input "button_2_repeat"
              - conditions: "{{ type == 'short_release' }}"
                sequence: !input "button_2_short_release"
              - conditions: "{{ type == 'long_release' }}"
                sequence: !input "button_2_long_release"
      - conditions: "{{ subtype == 3 }}"
        sequence:
          - chosse:
              - conditions: "{{ type == 'initial_press' }}"
                sequence: !input "button_3_initial_press"
              - conditions: "{{ type == 'long_press' }}"
                sequence: !input "button_3_long_press"
              - conditions: "{{ type == 'repeat' }}"
                sequence: !input "button_3_repeat"
              - conditions: "{{ type == 'short_release' }}"
                sequence: !input "button_3_short_release"
              - conditions: "{{ type == 'long_release' }}"
                sequence: !input "button_3_long_release"
      - conditions: "{{ subtype == 4 }}"
        sequence:
          - chosse:
              - conditions: "{{ type == 'initial_press' }}"
                sequence: !input "button_4_initial_press"
              - conditions: "{{ type == 'long_press' }}"
                sequence: !input "button_4_long_press"
              - conditions: "{{ type == 'repeat' }}"
                sequence: !input "button_4_repeat"
              - conditions: "{{ type == 'short_release' }}"
                sequence: !input "button_4_short_release"
              - conditions: "{{ type == 'long_release' }}"
                sequence: !input "button_4_long_release"
